### PR TITLE
Revert "100% -> 50%"

### PR DESCRIPTION
**Pull request by matthew-andrews**
Reverts Financial-Times/next-user-model#27 :joy: 

WIP — need to also fix a bug

### CODE REVIEW

**Comment by matthew-andrews** [comment]
@keirog

**Comment by matthew-andrews** [comment]
wow this is on travis

**Comment by keirog** [comment]
Yep, super unloved repo!

**Comment by keirog** [comment]
What's the bug?

**Comment by matthew-andrews** [comment]
it was this:
https://github.com/Financial-Times/next-user-model/pull/28/files#diff-541b95c95bad6099c84077e8f995e22fR65

:smile:

**Comment by keirog** [comment]
… :+1:

**Pull request merged**
